vaadin/router

- README.md
(after making the repo public and switching to the public Travis)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/92)
> switch the build status badge to the public Travis

- demo/demo-shell.html
- demo/vaadin-router-navigation-trigger-demos.html
- demo/vaadin-router-redirect-demos.html
- demo/vaadin-router-route-actions-demos.html
- index.click.js
- index.js
- rollup.config.js
- src/router-config.js
- src/router.js
- test/router.spec.html
Closes #88 
Note: also incorporates small change in tests, especially the `should update the history state after navigation` test was looking confusing with the existing setup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/96)
> Use click navigation trigger by default

- src/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/106)
> Remove redundant promise wrapper.

- src/resolver/resolver.js
- src/router.js
- test/router.spec.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/105)
> Log route path if error is uncaught.

- test/router.spec.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/119)
> Fix action test.

- demo/vaadin-router-lazy-loading-demos.html
DX test finding.
Depends on vlukashov/vaadin-demo-helpers#6 in the sense of updating docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/118)
> Update lazy loading demo to hide internal stuff

- demo/vaadin-router-redirect-demos.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/120)
> fix the `redirectFrom` documentation

- demo/vaadin-router-basic-demos.html
- demo/vaadin-router-lazy-loading-demos.html
- demo/vaadin-router-route-parameters-demos.html
- docs/vaadin-router/demo/vaadin-router-basic-demos.html
- docs/vaadin-router/demo/vaadin-router-lazy-loading-demos.html
- docs/vaadin-router/demo/vaadin-router-route-parameters-demos.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/123)
> Fix typos in demos

- src/router.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/132)
> Remove context from element.

- src/resolver/matchRoute.js
- src/resolver/resolver.js
- src/router.js
- test/resolver/resolver.spec.js
- test/router/dynamic.redirect.spec.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/139)
> Activate all routes.

- test/test-pushstate-throttler.html
(skip if tests are run via test/index.html?no-throttle)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/150)
> add an option to skip pushState throttling in tests

- test/router/dynamic.redirect.spec.html
- test/router/lifecycle-events.spec.html
- test/router/test-utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/163)
> Extract common test method to test-utils.js

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/168)
> Use working bundle size badge

- test/router/test-utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/177)
> Fix IE11 tests.

- demo/vaadin-router-lifecycle-callbacks-demos.html
- src/documentation/web-component-interface.js
- src/router.js
- test/router/lifecycle-events.spec.html
- test/router/parent-layouts.spec.html
- test/router/test-utils.js
Closes #166
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/174)
> Support 'onAfterLeave' callback.

- package.json
- src/triggers/triggerNavigation.js
- test/resolver/matchPath.spec.js
- test/resolver/matchRoute.spec.js
- test/router/lifecycle-events.spec.html
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/179)
> Log difference in lifecycle callbacks.

- demo/demos.json
- demo/vaadin-router-animated-transitions-demos.html
- rollup.config.js
- src/router.js
- src/transitions/animate.js
- test/index.coverage.html
- test/router/lifecycle-events.spec.html
- test/router/router.spec.html
- test/test-suites.js
- test/transitions/animate.spec.html
Fixes #42
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/164)
> Add animated transitions

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/189)
> Prepare 0.3.0 release

- src/router.js
- test/router/dynamic-redirect.spec.html
- test/router/lifecycle-events.spec.html
- test/router/router.spec.html
Fixes #145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/196)
> fail if there are more than 256 redirects for a path

- src/router.js
- test/router/dynamic-redirect.spec.html
- test/router/lifecycle-events.spec.html
- test/router/router.spec.html
Fixes #144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/194)
> add support for multiple redirects

- src/resolver/matchRoute.js
- src/resolver/resolver.js
- src/router.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/198)
> use `__children` as the primary data source

- src/resolver/generateUrls.js
- src/resolver/matchRoute.js
- src/resolver/resolver.js
- src/router.js
- test/router/router.spec.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/197)
> Store children in route.__children

- src/resolver/generateUrls.js
- src/resolver/matchRoute.js
- src/resolver/resolveRoute.js
- src/resolver/resolver.js
- src/router.js
- src/triggers/popstate.js
- src/utils.js
- test/resolver/resolver.spec.js
- test/router/lifecycle-events.spec.html
- test/router/router.spec.html
Closes #27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/185)
> Add routing JS API

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/204)
> Prepare 0.4.0 release

- src/router.js
- test/router/lifecycle-events.spec.html
- __setOutletContent -> __addAppearingContent
- __removePendingContent -> __removeAppearingContent
- __removeOldOutletContent -> __removeDisappearingContent
- __removeOutletContent -> removeDomNodes
- this.__oldContent -> this.__disappearingContent
- this.__newContent -> this.__appearingContent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/216)
> simplify and comment the code that adds / removes outlet content

- src/resolver/matchRoute.js
- src/resolver/resolver.js
- src/router.js
- src/utils.js
- test/resolver/matchRoute.spec.js
- test/resolver/resolver.spec.js
- test/router/parent-layouts.spec.html
- test/router/router.spec.html
Fixes #205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/215)
> Ensure resolved chain matches initial pathname

- demo/vaadin-router-animated-transitions-demos.html
- src/resolver/resolver.js
- src/router.js
- test/resolver/resolver.spec.js
- test/router/lifecycle-events.spec.html
- test/router/router.spec.html
- test/router/test-utils.js
Fixes #187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/221)
> Run lifecycle callbacks when only route params change

- src/router.js
- test/router/router.spec.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/225)
> change the result of router.ready from outlet to location

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/227)
> Prepare 1.0.0-rc.0 release

- src/router.js
- test/router/parent-layouts.spec.html
Fixes #217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/230)
> fix 404 when a parent route path ends with a slash

- package.json
- src/router-meta.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/235)
> add vaadin-usage-statistics to collect anonymous stats when the app runs in the dev mode

- package.json
- yarn.lock
fixes #232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/238)
> update to the latest path-to-regexp (2.2.1)

- analysis.json
- docs/vaadin-router/analysis.json
- src/documentation/location.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/242)
> fix a typo in the Location.redirectFrom docs

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/243)
> mention vaadin-usage-statistics in the README

- README.md
- package.json
- src/router-config.js
- src/router-meta.js
- test/router/router.spec.html
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/257)
> Re-enable usage statistics for 1.1.0

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/258)
> Prepare 1.1.0 release

- test/router/router.spec.html
- test/router/test-utils.js
+ improve a test helper method (more meaningful assertion message)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/267)
> (chore) move related test cases closer to each other

- src/router.js
- src/utils.js
- test/router/router.spec.html
Fixes #273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/274)
> fix(router): correct error message when action returns null-proto Object

- src/router.js
- test/router/router.spec.html
Fixes #265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/275)
> fix(router): enable further route resolution if action returns HTMLElement

- demo/vaadin-router-code-splitting-demos.html
- demo/vaadin-router-getting-started-demos.html
- demo/vaadin-router-lifecycle-callbacks-demos.html
- demo/vaadin-router-redirect-demos.html
- demo/vaadin-router-route-parameters-demos.html
Fixes #269
Depends on vaadin/vaadin-demo-helpers#56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/279)
> fix(demos) use target="_parent" for links to API docs

- demo/vaadin-router-route-actions-demos.html
- src/resolver/resolver.js
- src/router.js
- src/utils.js
- test/router/lifecycle-events.spec.html
- test/router/router.spec.html
Fixes #271
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/277)
> fix(router): ignore all unknown action result values

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/289)
> fix(ci): use Firefox 62.0 in Travis for now

- src/router.js
- test/router/router.spec.html
Fixes #300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/303)
> fix(route): ensure getUrl() works as expected on router.location

- yarn.lock
fix the security issues reported by `dependabot`
Affected packages:
- handlebars
- js-yaml
- pem
- fstream
- axios
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/335)
> chore: upgrade npm dependencies

- src/router.js
- test/router/router.spec.html
Fixes #342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/344)
> fix(router): enable rendering HTMLElement created without using context.component

- src/router.js
- test/router/router.spec.html
Fixes #356
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/359)
> fix: preserve search and hash on the first render

- src/router.js
- test/router/lifecycle-events.spec.html
Fixes #329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/365)
> fix: keep the url when the context does not change

- src/router.js
- test/router/router.spec.html
Fixes #366
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/368)
> fix: get search and hash only if given a context

- gen-tsd.json
- package.json
- src/router.js
- test/router/router.spec.html
Fixes #357 (and possibly #360 as well but need to be checked)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/375)
> fix: render correctly if reusing the same instance or same tagName

- interfaces.d.ts
- src/documentation/location.js
- src/router.js
- test/router/lifecycle-events.spec.html
- test/router/router.spec.html
- test/router/url-for.spec.html
Fixes #355 #360 #361 #311
Closes #331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/370)
> fix: events and detach/re-attach (#355, #361, #360, #311, #331)

- gulpfile.js
- package.json
- src/router-meta.js
- yarn.lock
This makes sure that the version in the source code in `router-meta.js` matches the version in npm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/384)
> fix: update the Router version in meta

- package.json
- src/router.js
- test/router/dynamic-redirect.spec.html
- test/router/lifecycle-events.spec.html
- test/router/parent-layouts.spec.html
Fixes: #391
Fixes: #392 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/393)
> update previousContext and do not remove layout custom content when reusing chain

- demo/vaadin-router-route-actions-demos.html
- demo/vaadin-router-route-parameters-demos.html
Fixes #56
Depends on #396
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/397)
> docs: add demos for search and hash usage

- analysis.json
- docs/vaadin-router/analysis.json
- docs/vaadin-router/demo/demo-shell.html
- src/router.js
- test/router/dynamic-redirect.spec.html
- test/router/router.spec.html
Fixes #324
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/406)
> fix: add browser history states for non-initial redirects

- analysis.json
- docs/vaadin-router/analysis.json
- docs/vaadin-router/demo/demo-shell.html
- src/router.js
- test/router/lifecycle-events.spec.html
Fixes #340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/407)
> fix: ensure location-changed event is timed after window.location update

- package.json
- src/resolver/resolver.js
- src/router.js
- test/router/parent-layouts.spec.html
Fixes #284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/437)
> fix(router): enable matching fallback sibling routes

- src/router.js
- test/router/parent-layouts.spec.html
Fixes #428
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/439)
> fix: update location when reusing parents

- test/router/parent-layouts.spec.html
- test/test-pushstate-throttler.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/440)
> test: fix Safari errors in CI

- interfaces.d.ts
Addresses #477.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/478)
> feat: add RouteWithAnimation interface to type definition file

- interfaces.d.ts
Fix #511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/512)
> Type the location-changed event

- .travis.yml
- wct.conf.js
chore: update CI browser capabilities (#529)
(cherry picked from commit 286a0e1ac3ce9a8926d9c800b3a7a06cabddb4bc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/540)
> Cherry pick 1.x

- package.json
- rollup.config.js
- src/resolver/matchPath.js
- src/resolver/path-to-regexp.js
- src/resolver/resolver.js
- test/index.coverage.html
- wct.conf.js
- yarn.lock
~Depends on #450~
Fix #347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/351)
> chore: update path-to-regexp

- analysis.json
- demo/vaadin-router-code-splitting-demos.html
- interfaces.d.ts
- src/router.js
- src/utils.js
- test/router/lifecycle-events.spec.html
- test/router/router.spec.html
Fix #442
The bundle size changes from `7.74KB` to `7.36KB` 🎉 
Note: This is a **breaking change**.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/464)
> Drop support for route.bundle

- .travis.yml
- src/triggers/click.js
- test/triggers/click.spec.html
cherry-pick the scroll to top fix to 1.x, so that people who don't want a breaking change could get it as well.
> 1.x cherry pick
