vaadin/router

src/router.js
src/triggers/popstate.js
test/router.spec.html

Fixes #89
Depends on #96 for the demo and tests (but not implementation)
- check "Custom Route Action" demo
- click the "All Users" link
- see the `Statistics on URL visits: { "/users": 1 }}`
Same results in `"/users": 2` when running fix on top of the master, most likely because of the fact that `triggerNavigation.js` is bundled into two different locations at the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/98)

Prevent duplicate navigation event for same pathname

---

src/resolver/resolver.js
test/router.spec.html

Currently, setting route `component` to something that is not a valid tag name, e. g. `src/x-home-view.html` throws the following error:
```
TypeError: Cannot assign to read only property 'code' of object ''
```
This happens because [DOMException](https://developer.mozilla.org/en-US/docs/Web/API/DOMException) has its own, legacy `code` property which is read only.
That error is quite confusing. As a developer, I expect the exception to look like this:
```
Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('src/x-home-view.html') is not a valid name.
```
Added a check and a test ensuring we rethrow the exception correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fix catching DOMException: do not override read only code property

---

src/triggers/click.js
src/triggers/popstate.js
test/router.spec.html
test/triggers/click.spec.html
test/triggers/popstate.spec.js

Improve the same origin check on `<a>` in-app links.
Fixes #87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/101)

Improve the same origin link detection

---

package.json

- turn on compression and names mangling (consider all properties starting with a double underscore private and mangle them)
- bundle size minified gzipped: 4.31 kB (was 5.44 kB)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/110)

enable better minification with uglify-es

---

bs-config.js
demo/demos.json
demo/vaadin-router-basic-demos.html
demo/vaadin-router-lazy-loading-demos.html
demo/vaadin-router-navigation-trigger-demos.html
demo/vaadin-router-redirect-demos.html
demo/vaadin-router-route-actions-demos.html
demo/vaadin-router-route-parameters-demos.html

- rewrite the demo descriptions to make them use more consistent terminology
- rename "Basic" to "Getting Started"
- reorder the demos so that navigation triggers and custom actions are in the end, after more basic concepts as redirects and lazy loading
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/115)

update demo descriptions, reorder tabs 

---

demo/vaadin-router-route-actions-demos.html
src/router.js
test/router/dynamic.redirect.spec.html
test/router/router.spec.html

Based on https://github.com/vaadin/vaadin-router/pull/137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/138)

Fill context with the information on which route triggered the function.

---

src/router.js
test/resolver/resolver.spec.js
test/router/dynamic.redirect.spec.html
test/router/lifecycle-events.spec.html
test/router/router.spec.html
test/test-suites.js

Closes #23 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/151)

Support `onBeforeEnter`, `onBeforeLeave` and `onAfterEnter` navigation lifecycle events.

---

.travis.yml
README.md
package.json

- use SemVer (start with 0.1.0)
-  remove the npm postinstall script
it works find when running `npm install` after cloning the repo, but breaks when trying to install `@vaadin/router` as a dependency in another project with `npm install @vaadin/router`
-  add an npm install snippet to README
closes #34
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/155)

add npm install snippet to README

---

package.json
rollup.config.js

Fixes #156 
Let's not use `.mjs` while it is considered to be more a node-specific.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/157)

Restore using .js extension for better tools compatibility

---

package.json

Bumping version due to `.mjs` bundle removal.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/158)

Prepare 0.2.0 release

---

demo/vaadin-router-redirect-demos.html

The same demo shows how to redirect from the `onBeforeEnter` lifecycle callback (see the `x-admin-view` custom element) and from a custom route action (see the `/logout` route).
Closes #24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/159)

add a dynamic redirect demo (from onBeforeEnter)

---

demo/vaadin-router-getting-started-demos.html
package.json
test/index.html

(since it does not work with the babel transform-es2015-classes plugin)
feature request in babel/minify: https://github.com/babel/minify/issues/358
bump the version to 0.2.1
Fixes: #160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/165)

disable property names mangling in UMD builds

---

src/router.js
test/router/dynamic-redirect.spec.html
test/router/router.spec.html

Fixes #141
By replacing state, we ensure that pressing "back" does not return us back to the URL which will redirect again. The expected behaviour is already documented in demos, so no demo needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/186)

Use history.replaceState when redirecting

---

src/router.js
test/router/router.spec.html

Fixes #183 
Instead of silently skipping navigation if no routes are configured, proceed with navigation and handle misconfiguration as any other router issue, i.e. log an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/184)

add an informative error message when router is used unconfigured

---

src/router-config.js
src/router-meta.js
test/router/router.spec.html

Part of #32, as the `vaadin-usage-statistics` assumes the Custom Element definition
See https://github.com/vaadin/vaadin-usage-statistics/blob/master/vaadin-usage-statistics.js#L82
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/192)

Add vaadin-router-meta custom element class

---

src/router.js
src/utils.js
test/router/router.spec.html

Based on the DX test feedback from #67 
Removed the test previously bypassing `null` and `undefined`, added a new one.
Also reorganised the test suites:
- there is now separate suite for order of execution (action, bundle, redirect)
- moved the "children function" suite one level above to align with others
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/210)

Throw exception if children result is not array or object

---

package.json
rollup.config.js

Fixes #207 
The UMD bundles is not processed correctly by `polymer-cli`, which has its own AMD transform, resulting in `window.define` is true, but `window.define.amd` is false.
Leaving ES module as the only entry in package.json for now. For those who need UMD bundle, it is still there but should be included manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/208)

Remove UMD bundle from package.json

---

src/router.js
test/router/lifecycle-events.spec.html
test/router/parent-layouts.spec.html

- reverse the order of calling the onAfterLeave callbacks: now from the leafs to the root
- call 'removeChild' after 'onAfterLeave' to make sure the nested children are removed from the cached view components
Fixes #206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/214)

Fix the issue when a nested content remains on navigation

---

src/router.js
test/router/parent-layouts.spec.html

Regression from #221 
Now we no longer use "early caching" but creating new DOM node before obtaining diverged index, so this fixes the references to the unchanged element in the new chain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/223)

Fix parent layouts: update references to the unchanged elements

---

demo/demo-elements/user.bundle.html
demo/demo-elements/user.bundle.js
demo/demo-elements/x-image-view.html
demo/demo-elements/x-knowledge-base.html
demo/demo-elements/x-login-view.html
demo/demo-elements/x-profile-view.html
demo/demo-elements/x-user-not-found-view.html
demo/demo-elements/x-user-numeric-view.html
demo/demo-elements/x-user-profile.html
demo/vaadin-router-getting-started-demos.html
demo/vaadin-router-lifecycle-callbacks-demos.html
demo/vaadin-router-redirect-demos.html
demo/vaadin-router-route-actions-demos.html
demo/vaadin-router-route-parameters-demos.html
src/documentation/location.js
src/documentation/namespace.js
src/documentation/web-component-interface.js
src/router.js
test/router/dynamic-redirect.spec.html
test/router/lifecycle-events.spec.html
test/router/parent-layouts.spec.html
test/router/router.spec.html
test/router/test-utils.js

Use similar data structures across all public APIs that expose a similar set of properties:
- custom route actions
- lifecycle callbacks
- global router events
- the property set by Vaadin.Router on view Web Components
- the router JS API (`router.location`)
Closes #209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/222)

Use `location` and `commands` instead of `context` in the public API

---

src/router.js

`Promise.all([])` is a supported behavior (it immediately resolves with an `undefined` result). That is, checking that promises is not empty is redundant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/224)

shorten the code in __animateIfNeeded

---

bower.json

The iframe-renderer and other features from the custom form got merged upstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/233)

stop using a custom fork of vaadin-demo-helpers

---

package.json
wct.conf.js
yarn.lock

Let's sync with the skeleton and use this package, as it appears to use more recent dependencies.
```
Statements   : 93% ( 239/257 )
Branches     : 83.9% ( 172/205 )
Functions    : 90.57% ( 48/53 )
Lines        : 93.65% ( 236/252 )
```
```
Statements   : 93.98% ( 281/299 ), 13 ignored
Branches     : 84.93% ( 186/219 ), 14 ignored
Functions    : 95.56% ( 43/45 ), 2 ignored
Lines        : 94.56% ( 278/294 )
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/239)

Use wct-istanbul plugin for coverage

---

wct.conf.js

From https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-BrowserVersion
> Default to Latest Version of Chrome or Firefox
> If you want to use the latest stable version of Google Chrome or Firefox that Sauce supports, you can use "version": "latest". You can also use "version": "latest-1" or "version": "latest-2", etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/240)

Use 'latest' and 'latest-1' for SauceLabs platforms

---

test/router/router.spec.html

in IE11 Mutation Observer is not very predictable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/263)

fix an unstable test for animated transitions

---

package.json

The field was there initially, but it has been removed in #130. 
Recently there has been a request to put it back, e.g. to be compatible with @pikapkg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/336)

chore(package): restore using module field

---

.travis.yml
wct.conf.js

SauceLabs removed support for older Safari versions:
```
iOS Simulator iphone 11.0 Tests passed
Test run ended in failure: Misconfigured -- Unsupported OS/browser/version/device combo: OS: 'unspecified', Browser: 'iphone', Version: '10.0.', Device: 'iPhone Simulator'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/337)

test: update browser versions to fix build

---

src/router.js
test/router/parent-layouts.spec.html

Call lifecycle callbacks in the context of the deepest child route instead of calling them in the context of the top-most parent route. The parent context does not have route params, whereas the child context does.
Fixes #321
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/322)

pass the correct route params to lifecycle callbacks in child routes

---

package.json

Interesting for me to use the typescript branch for example 🙂
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/367)

fix: add prepare script to allow usage via git directly

---

src/router.js

Use `WeakMap` instead of `WeakSet` because `WeakSet` is not supported by  IE11.
Follow up of #375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/379)

fix: use WeakMap instead of WeakSet

---

src/router.js

I tested with saucelabs. After this PR, `master` should be green again
Follow up #375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/380)

fix: use indexOf instead of includes

---

package.json
src/router.js
test/router/lifecycle-events.spec.html
test/router/router.spec.html

Stop executing lifecycle callbacks (`action`, `onBeforeLeave`, `onBeforeEnter`, `onAfterEnter`, `onAfterLeave`) when the current render is out of date because there is a new render.
Fixes #378
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/385)

fix: prevent executing old render lifecycle callbacks

---

.travis.yml

For unknown reasons, `wct --env saucelabs` doesn't work on `bionic` but it is fine in `xenial`. So I change it to `xenial` to keep the build green on master
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/394)

chore: fix travis build

---

src/router.js
test/router/lifecycle-events.spec.html
test/router/router.spec.html

Connected to #56
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/396)

fix: ensure search and hash in context, location, and lifecycle

---

analysis.json
docs/vaadin-router/analysis.json
docs/vaadin-router/demo/demo-shell.html
src/router.js
test/router/router.spec.html

Before this PR, Router takes `base href` as `baseUrl` which is later resolved against `document.baseURI` regardless it's a relative one or not.
Semantically, `baseUrl` shouldn't be in relative form because it is the prefix of every route in the Router.
This PR resolves the relative `base href` to be an absolute pathname before setting it as the `baseUrl`.
Fixes #409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/410)

fix: change default baseUrl to be an absolute pathname 

---

package.json
tsconfig.json
yarn.lock

Fixes #411 
We encountered the error caused by `'vfile-message'` in the components, too.
Setting `skipLibCheck` seems like a proper way to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/420)

chore(tsconfig): set skipLibCheck: true

---

demo/vaadin-router-getting-started-demos.html
demo/vaadin-router-navigation-trigger-demos.html
src/triggers/click.js
test/triggers/click.spec.html

Tried to go by the checklist in the issue one by one but could not do this:
> In the same demo also mention how to exclude multiple URLs at once with a custom action
Could you help me on this one @vlukashov?
Fixes #325 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/421)

feat: added router-ignore attribute to ignore the links (#325)

---

analysis.json
demo/vaadin-router-navigation-trigger-demos.html
docs/vaadin-router/analysis.json
docs/vaadin-router/demo/demo-shell.html
docs/vaadin-router/demo/vaadin-router-navigation-trigger-demos.html
interfaces.d.ts
src/documentation/location.js
src/documentation/web-component-interface.js
src/router.js
src/triggers/click.js
src/triggers/popstate.js
test/typescript/compile_fixture.ts

Depends on #426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/427)

feat(typescript): extract type definitions from Router namespace

---

demo/vaadin-router-getting-started-demos.html
demo/vaadin-router-lifecycle-callbacks-demos.html

Fixes #423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/432)

docs(typescript): add examples of TypeScript location and lifecycle interfaces

---

test/router/parent-layouts.spec.html

Fixes #307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/438)

test(router): matching child not under first parent

---

demo/vaadin-router-lifecycle-callbacks-demos.html
src/router.js
test/router/lifecycle-events.spec.html

This could fix a couple of issues in Flow
https://github.com/vaadin/flow/issues/7665
https://github.com/vaadin/flow/issues/7572 
https://github.com/vaadin/flow/issues/8071
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/456)

Do lifecycle callbacks even on the same route

---

.travis.yml
wct.conf.js

This fixes newer Android tests that currently fail to run on master in CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-router/529)

chore: update CI browser capabilities

---

index.polyfilled.js
src/resolver/generateUrls.js
src/resolver/matchPath.js
src/resolver/resolver.js
src/router.js
test/.eslintrc.json
test/router/router.spec.html
test/router/url-for.spec.html

follow up on https://github.com/vaadin/vaadin-router/pull/351
- since `path-to-regexp` 3.1.0 the way of passing options into the `tokensToFunction()` function has changed (see [#191](https://github.com/pillarjs/path-to-regexp/pull/191)).
- since `path-to-regexp` 4.0.0 the default exports have changed from a module object to individual functions (see [4.0.0](https://github.com/pillarjs/path-to-regexp/releases/tag/v4.0.0)).
- since `path-to-regexp` 5.0.0 the default value for the optional `encode` parameter in the `tokensToFunction()` function has changed (see [5.0.0](https://github.com/pillarjs/path-to-regexp/releases/tag/v5.0.0)).
- since `path-to-regexp` 6.0.0 the `repeat` and `modifier` properties on route regexp keys were removed (see …

fix failing tests after path-to-regexp 6.2.0 update

---

src/triggers/click.js
test/triggers/click.spec.html

Apply @abdonrd 's [patch](https://github.com/IBM/pwa-lit-template/blob/main/patches/@vaadin+router+1.7.2.patch) to https://github.com/vaadin/vaadin-router/issues/43. 
Not optimal, but maybe a good first step.

fix: scroll to top on click event

---

src/resolver/resolver.js
src/router.js
test/resolver/resolver.spec.js
test/router/router.spec.html

Fixes #517
When not set explicitly, the router constructor discovers `baseUrl`
using the `<base href>` value and initial document URL. However, only
the pathname from the discovered base URL was taken for the default
value of the `baseUrl` property. In case of initial pathname starting with
double slash `//`, such a value was then throwing `Invalid URL` error when
used as the URL constructor’s first argument.
This changes the default value discovery of `baseUrl`, so that it uses
an actual URL instead of only pathname to avoid throwing errors.

fix: avoid URL-confusing default pathname in baseUrl

---

src/router.js
test/router/router.spec.html

Fixes #523. Also converted to static helper instead of scoped function for testability.

fix: removeDomNodes with HTMLCollection

---

index.polyfilled.js
src/resolver/resolver.js

In Safari before 14.0, URL constructor throws when the `base` second
argument is `undefined`. This change prevents invoking URL with
undefined base argument when the argument is omitted in `__createUrl`.

fix: skip undefined base argument in URL constructor

---

analysis.json
demo/vaadin-router-route-parameters-demos.html
demo/vaadin-router-url-generation-demos.html
docs/iron-component-page/iron-component-page.html
docs/vaadin-router/analysis.json
docs/vaadin-router/demo/demo-shell.html
docs/vaadin-router/demo/vaadin-router-code-splitting-demos.html
docs/vaadin-router/demo/vaadin-router-route-parameters-demos.html
docs/vaadin-router/demo/vaadin-router-url-generation-demos.html
interfaces.d.ts
src/documentation/location.js
src/router.js
test/router/router.spec.html
test/typescript/compile_fixture.ts

For https://github.com/vaadin/vaadin-router/issues/498

feat: add searchParams for RouterLocation

---

README.md

The repository was renamed from `vaadin-router` to `router` so GitHub pages
links need to be updated as that doesn't seem to redirect automatically.

docs: fix demo and API docs links in readme

---

package.json

The `type` property of `package.json` may be used by frontend tooling (e.g Webpack, Vite) in determining whether the package's entry point is a conventional CJS or ES module. If no property is specified, the entry point may be treated as a CJS module. As an illustration, here is a warning that Vite shows when you import the Vaadin router:
> @vaadin/router doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
This PR explicitly sets the `type` property to `module` to avoid possible misinterpretation.
Related to vaadin/flow#12574

chore: set type to module in package.json
